version: '2'
services:
    wiremock:
        image: 'wiremock/wiremock:latest'
        container_name: wiremock
        volumes:
            - ./__files/:/home/wiremock/__files/
            - ./mappings/:/home/wiremock/mappings/
        ports:
            - '8383:8080'
